### ISSUE TITLE
Dynamic Filters

### ISSUE THREAD

**Issue by NCEghtebas** [TUMFARSynchrony/experimental-hub#121]
- [ ] what aspects of filter_new needs ot be changed? (e.g. add a config for state of filter?)
- [ ] validate dict
- [ ] dynamically generate filter_new.json in backend
- [ ] refactor filters with parameters in filter definition.

**Comment by tobifb** [comment]
Basically, there are three steps to generate filter.json dynamically:

- [ ] use the already existing new_filter.json in the frontend, change all validation methods in the backend so that it validates the new_filter.json file
- [ ] dynamically generate filter_new.json file in the backend to reduce complexity for adding a new filter (only have one file to change)
- [ ] don't save the filter anymore, use instead API call from the frontend to receive the filter_new.json as data
